// web/src/lib/components/Navigation.svelte
<script lang="ts">
  import { page } from '$app/stores';
  
  // Extract testId from URL params
  $: testId = $page.params.testId;
  $: isResultPage = $page.url.pathname.startsWith('/results/') && testId;
  $: currentPath = $page.url.pathname;
  
  function preventClick(event: Event) {
    event.preventDefault();
  }
</script>

<nav class="common-nav">
  {#if isResultPage}
    <a 
      href="/results/{testId}/overview" 
      class="nav-link"
      class:active={currentPath.endsWith('/overview')}
    >
      Overview
    </a>
    <a 
      href="/results/{testId}/metrics" 
      class="nav-link"
      class:active={currentPath.endsWith('/metrics')}
    >
      Metrics
    </a>
    <a 
      href="/results/{testId}/filmstrip" 
      class="nav-link"
      class:active={currentPath.endsWith('/filmstrip')}
    >
      Filmstrip
    </a>
    <a 
      href="/results/{testId}/video" 
      class="nav-link"
      class:active={currentPath.endsWith('/video')}
    >
      Video
    </a>
    <a 
      href="/results/{testId}/waterfall" 
      class="nav-link"
      class:active={currentPath.endsWith('/waterfall')}
    >
      Waterfall
    </a>
    <a 
      href="/results/{testId}/resources" 
      class="nav-link"
      class:active={currentPath.endsWith('/resources')}
    >
      Resources
    </a>
    <a 
      href="/results/{testId}/console" 
      class="nav-link"
      class:active={currentPath.endsWith('/console')}
    >
      Console
    </a>
    <a 
      href="/results/{testId}/bottlenecks" 
      class="nav-link"
      class:active={currentPath.endsWith('/bottlenecks')}
    >
      Bottlenecks
    </a>
    <a 
      href="/results/{testId}/config" 
      class="nav-link"
      class:active={currentPath.endsWith('/config')}
    >
      Config
    </a>
  {:else}
    <span class="nav-link disabled">Overview</span>
    <span class="nav-link disabled">Metrics</span>
    <span class="nav-link disabled">Filmstrip</span>
    <span class="nav-link disabled">Video</span>
    <span class="nav-link disabled">Waterfall</span>
    <span class="nav-link disabled">Resources</span>
    <span class="nav-link disabled">Console</span>
    <span class="nav-link disabled">Bottlenecks</span>
    <span class="nav-link disabled">Config</span>
  {/if}
</nav>

<style>
  .nav-link.active {
    background: var(--color-background-lighter);
    border-color: var(--color-accent);
    color: var(--color-accent);
  }
</style>

// web-react/src/components/Navigation.jsx
import { Link, useLocation, useParams } from 'react-router-dom';

function Navigation() {
  const location = useLocation();
  const params = useParams();
  const isResultPage = location.pathname.includes('/results/') && 
                       location.pathname.split('/').length > 3;
  const testId = isResultPage ? location.pathname.split('/')[2] : null;

  const isActive = (path) => {
    if (!testId) return false;
    return location.pathname === `/results/${testId}/${path}`;
  };

  return (
    <nav className="common-nav">
      {isResultPage ? (
        <>
          <Link 
            to={`/results/${testId}/overview`}
            className={`nav-link ${isActive('overview') ? 'active' : ''}`}
          >
            Overview
          </Link>
          <Link 
            to={`/results/${testId}/metrics`}
            className={`nav-link ${isActive('metrics') ? 'active' : ''}`}
          >
            Metrics
          </Link>
          <Link 
            to={`/results/${testId}/resources`}
            className={`nav-link ${isActive('resources') ? 'active' : ''}`}
          >
            Resources
          </Link>
          <Link 
            to={`/results/${testId}/waterfall`}
            className={`nav-link ${isActive('waterfall') ? 'active' : ''}`}
          >
            Waterfall
          </Link>
          <Link 
            to={`/results/${testId}/filmstrip`}
            className={`nav-link ${isActive('filmstrip') ? 'active' : ''}`}
          >
            Filmstrip
          </Link>
          <Link 
            to={`/results/${testId}/video`}
            className={`nav-link ${isActive('video') ? 'active' : ''}`}
          >
            Video
          </Link>
          <Link 
            to={`/results/${testId}/console`}
            className={`nav-link ${isActive('console') ? 'active' : ''}`}
          >
            Console
          </Link>
          <Link 
            to={`/results/${testId}/bottlenecks`}
            className={`nav-link ${isActive('bottlenecks') ? 'active' : ''}`}
          >
            Bottlenecks
          </Link>
          <Link 
            to={`/results/${testId}/config`}
            className={`nav-link ${isActive('config') ? 'active' : ''}`}
          >
            Config
          </Link>
        </>
      ) : (
        <>
          <span className="nav-link disabled">Overview</span>
          <span className="nav-link disabled">Metrics</span>
          <span className="nav-link disabled">Resources</span>
          <span className="nav-link disabled">Waterfall</span>
          <span className="nav-link disabled">Filmstrip</span>
          <span className="nav-link disabled">Video</span>
          <span className="nav-link disabled">Console</span>
          <span className="nav-link disabled">Bottlenecks</span>
          <span className="nav-link disabled">Config</span>
        </>
      )}
    </nav>
  );
}

export default Navigation;
