// web-svelte/src/lib/components/Tabs.svelte
<script lang="ts">
  import { page } from '$app/stores';
  
  $: currentPath = $page.url.pathname;
</script>

<header>
  <nav class="tabs">
    <a href="/" class="tab" class:active={currentPath === '/'}>Simple</a>
    <a href="/advanced" class="tab" class:active={currentPath === '/advanced'}>Advanced</a>
    <a href="/results" class="tab" class:active={currentPath === '/results'}>Results</a>
    <a href="/upload" class="tab" class:active={currentPath === '/upload'}>Upload</a>
  </nav>
</header>

<style>
  .tab.active {
    background: var(--color-background-lighter);
    border-color: var(--color-accent);
    color: var(--color-accent);
  }
</style>

// web-react/src/components/Tabs.jsx
import { Link, useLocation } from 'react-router-dom';

function Tabs() {
  const location = useLocation();

  const isActive = (path) => {
    if (path === '/' && location.pathname === '/') return true;
    if (path !== '/' && location.pathname.startsWith(path)) return true;
    return false;
  };

  return (
    <div className="tabs">
      <Link to="/" className={`tab ${isActive('/') ? 'active' : ''}`}>
        Simple
      </Link>
      <Link to="/advanced" className={`tab ${isActive('/advanced') ? 'active' : ''}`}>
        Advanced
      </Link>
      <Link to="/results" className={`tab ${isActive('/results') ? 'active' : ''}`}>
        Results
      </Link>
      <Link to="/upload" className={`tab ${isActive('/upload') ? 'active' : ''}`}>
        Upload
      </Link>
    </div>
  );
}

export default Tabs;
